### PR TITLE
Download all firmware releases.

### PR DESCRIPTION
**Pull request by brahma-dev**

### CODE REVIEW

**Comment by jlkalberer** [comment]
The PR looks fine but why don't you want to include RCs? It really shouldn't affect anything if they are downloaded as well.

**Comment by brahma-dev** [comment]
I remember it being that way. https://github.com/Brewskey/spark-protocol/blob/620d7acba9ef38aafa76f2be73937c98263c433b/src/scripts/update-firmware-binaries.js#L192

But I can remove the filter if you say so.

**Comment by jlkalberer** [comment]
Yeah, I think I removed them but added them back in because there wasn’t a good reason to filter. Generally I use ParticleDev and you can flash any version to your device. If you don’t have a good reason to filter them then let’s just keep everything.

Other than that, thanks for the diff!

**Comment by brahma-dev** [comment]
@jlkalberer Done.

**Pull request merged**
